### ISSUE TITLE
What r the build instructions for this?

### ISSUE THREAD

**Issue by richtong** [yodasoda1219/fe_engine#1]
Windows only?

**Comment by yodasoda1219** [comment]
Yes, for now. C# 9.0 is not yet supported on Mono and .NET Core, and is required by Newtonsoft.Json.
The only installable dependency is Mono, and can be downloaded from [here](https://www.mono-project.com/download/stable/). Make sure to install the version corresponding to the architecture you wish to build for.
To generate project files, run the included "windows-genprojects.bat" file. You can specify extra command-line arguments intended for premake by appending to the batch command.
For example, to target a different architecture, use --architecture=(x64, x86, arm64, etc.).

**Comment by richtong** [comment]
Ok thanks I'm happy to do a PR for your README so other know how to build :-)

**Comment by yodasoda1219** [comment]
OK so I forgot to close this issue, however I have updated the build system as to allow building on Linux and MacOS.
